apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-task1-backend
  labels:
    app: questionnaire-task1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-task1-backend
  template:
    metadata:
      labels:
        app: questionnaire-task1-backend
    spec:
      containers:
      - name: backend
        image: ronaldosssantos1/questionnaire-task1-backend:latest
        ports:
        - containerPort: 3000