apiVersion: v1
kind: Service
metadata:
  name: questionnaire-task1-backend-service
spec:
  selector:
    app: questionnaire-task1-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer