apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: questionnaire-task1-ingress
spec:
  rules:
  - host: questionnaire.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: questionnaire-task1-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: questionnaire-task1-backend-service
            port:
              number: 3000